CC = g++
CFLAGS = -wall -g

Render: main.o point.o square.o
	$(CC) $(CFLAGS) –o Render main.o Prism.o Line3D.o Point3d.o Screen.o Vector3D.o Space.o Sphere.o Polyhedron.o

main.o: main.cpp
	$(CC) $(CFLAGS) -c main.cpp

Prism.o: Prism.cpp
	$(CC) $(CFLAGS) -c .\src\Prism.cpp

Line3D.o: Line3D.cpp
	$(CC) $(CFLAGS) -c .\src\Line3D.cpp

Point3D.o: Point3D.cpp
	$(CC) $(CFLAGS) -c .\src\Point3D.cpp

Screen.o: Screen.cpp
	$(CC) $(CFLAGS) -c .\src\Screen.cpp

Vector3D.o: Vector3D.cpp
	$(CC) $(CFLAGS) -c .\src\Vector3D.cpp

Space.o: Space.cpp
	$(CC) $(CFLAGS) -c .\src\Space.cpp

Sphere.o: Sphere.cpp
	$(CC) $(CFLAGS) -c .\src\Sphere.cpp

Polyhedron.o: Polyhedron.cpp
	$(CC) $(CFLAGS) -c .\src\Polyhedron.cpp